# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "frostbitten"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Emil Palm"]
  s.date = "2013-02-02"
  s.description = "Gem that provides RCON commands for frostbite 2 engine games. BF3, BFBC2 and so on"
  s.email = "emil.palm@x86.nu"
  s.extensions = ["ext/frostbitten/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/.DS_Store",
    "ext/frostbitten/.DS_Store",
    "ext/frostbitten/Makefile",
    "ext/frostbitten/extconf.rb",
    "ext/frostbitten/src/frostbitten.c",
    "ext/frostbitten/src/frostbitten.h",
    "ext/frostbitten/src/header.c",
    "ext/frostbitten/src/header.h",
    "ext/frostbitten/src/message.c",
    "ext/frostbitten/src/message.h",
    "ext/frostbitten/src/word.c",
    "ext/frostbitten/src/word.h",
    "lib/frostbitten.rb",
    "spec/frostbitten_server_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb",
    "test/test_frostbitten.rb"
  ]
  s.homepage = "http://github.com/mrevilme/frostbitten"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Gem that provides RCON commands for frostbite 2 engine games. BF3, BFBC2 and so on"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

